### ISSUE TITLE
Tronxy X5SA Pro 400 comes with stack marlin firmware which is very limited

### ISSUE THREAD

**Issue by javlonsodikov** [Darkwulf183/Marlin-2.0.8-ALL-UI-Standart-Color-LVGL#2]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

After flashing with this firmware black screen. Also when connecting with a USB board not send any information back. 

### Bug Timeline

new bug

### Expected behavior

Screen should work

### Actual behavior

not sure

### Steps to Reproduce

my config 
#define V6_400_TITAN_TMC 1

### Version of Marlin Firmware

2.0.8

### Printer model

Tronxy x5sa pro 400  

### Electronics

stock hardware

### Add-ons

na

### Your Slicer

Cura

### Host Software

Cura

### Additional information & file uploads

ssss

**Comment by Darkwulf183** [comment]
No more issues are dealt with at this point. I have stopped the support via Youtube. So I will not test or fix anything anymore. The version ran flawlessly with over 6000 downloaders. Either you have a screen from the new ones on it, which are basically not supported by the old Marlin, or it didn't flash cleanly.
